modification  des regle eslit et package.json, installer axios,mise …
WildCodeSchool-2023-09/JS-RMT-React_If-Projet2-Obscuria pull request #3
Opened 2023-11-08 14:32 UTC by sebastienbaquet

…en place des cores,mise en place loder pour recuperer les films ,integration des films et mise en place css.

2023-11-10 15:00 UTC, GreG6431 approved these changes
Bon, tout est bien enlevé et modifié :'(

2023-11-10 15:33 UTC, Sarhane64 approved these changes
Ok pour moi

2023-11-14 08:49 UTC, jujuck requested changes

2023-11-14 08:49 UTC, jujuck commented on frontend/src/App.css
> +.contener {
Je pense que tu veux dire container ?

2023-11-14 08:49 UTC, jujuck commented on frontend/src/App.css
> +.carte {
Si le nommage des class est en anglais, alors il faut tout mettre en anglais

2023-11-14 08:49 UTC, jujuck commented on frontend/src/App.css
> +.carte {
Si la class carte est spécifique à un élément, alors il faut créer un fichier de style pour ce composant

2023-11-14 08:49 UTC, jujuck commented on frontend/src/App.css
> +  .carte {
Idem

2023-11-14 08:49 UTC, jujuck commented on frontend/src/App.jsx
> +    <div className="appcontener">
Je n'ai pas trouvé de class css appcontener mais seulement contener. A vérifier et renommer container

2023-11-14 08:49 UTC, jujuck commented on frontend/src/components/Film.jsx
> +    <div className="contener">
Renommer container

2023-11-14 08:49 UTC, jujuck commented on frontend/src/components/Film.jsx
> +          <div className="carte" key={film.id}>
Faire un composant avec props

2023-11-14 13:51 UTC, GreG6431 approved these changes
Ok pour les modifications

2023-11-14 13:53 UTC, Sarhane64 approved these changes

2023-11-14 14:40 UTC, jujuck approved these changes

2023-11-14 14:40 UTC, merged