Title Footer avec liens url vers sites reseaux sociaux
WildCodeSchool-2023-09/JS-RMT-React_If-Projet2-Obscuria pull request #4
Opened 2023-11-10 15:09 UTC by GreG6431

2023-11-10 15:13 UTC, sebastienbaquet approved these changes
ok pour validation

2023-11-10 15:30 UTC, Sarhane64 approved these changes
Ok pour moi

2023-11-14 09:06 UTC, jujuck requested changes

2023-11-14 09:06 UTC, jujuck commented on frontend/src/App.css
> +.contener {
A voir avec Sebastien

2023-11-14 09:06 UTC, jujuck commented on frontend/src/components/Footer.jsx
> +      <h1 className="title-website-footer">OBSCURIA</h1>
Mettre un h3

2023-11-14 09:06 UTC, jujuck commented on frontend/src/components/Footer.jsx
> +          <a href="https://www.facebook.com">
Ajouter target ="_blank" en attribut et noreferer sur les a

2023-11-14 09:06 UTC, jujuck commented on frontend/src/components/Footer.jsx
> +          <a href="https://www.facebook.com">
Faire un composant avec le a et le i

2023-11-14 09:06 UTC, jujuck commented on frontend/src/components/Footer.jsx
> +          <a href="/about">ABOUT</a>
Utiliser un  Link, c'est de la navigation interne

2023-11-14 09:06 UTC, jujuck commented on frontend/src/components/Footer.jsx
> +          <a href="/about">ABOUT</a>
Non; ne pas mettre le lien tant que la page n'existe pas (C'est une autre US)

2023-11-14 10:34 UTC, GreG6431 commented on frontend/src/App.css
> +.contener {
Vu

2023-11-14 10:34 UTC, GreG6431 commented on frontend/src/components/Footer.jsx
> +      <h1 className="title-website-footer">OBSCURIA</h1>
Fait

2023-11-14 10:38 UTC, GreG6431 commented on frontend/src/components/Footer.jsx
> +          <a href="https://www.facebook.com">
Fait

2023-11-14 14:18 UTC, GreG6431 commented on frontend/src/components/Footer.jsx
> +          <a href="/about">ABOUT</a>
Fait

2023-11-15 08:28 UTC, GreG6431 commented on frontend/src/components/Footer.jsx
> +          <a href="https://www.facebook.com">
Fait

2023-11-15 13:51 UTC, jujuck approved these changes

2023-11-15 13:51 UTC, jujuck commented on frontend/src/App.jsx
> +
Suppression des lignes de commentaires

2023-11-15 13:51 UTC, jujuck commented on frontend/src/App.css
> +.conteneur-low {
A vérifier mais à supprimer je pense, doublon avec le footer

2023-11-15 13:56 UTC, merged