ajout de emailjs  formulaire et de son css
WildCodeSchool-2023-09/JS-RMT-React_If-Projet2-Obscuria pull request #5
Opened 2023-11-10 15:27 UTC by Sarhane64

2023-11-10 15:42 UTC, sebastienbaquet approved these changes
super  formulaire

2023-11-14 08:58 UTC, jujuck requested changes

2023-11-14 08:58 UTC, jujuck commented on frontend/src/components/Form.jsx
> +        "service_uvr52fi",
Passer ces valeurs en variables d'environnement

2023-11-14 08:58 UTC, jujuck commented on frontend/src/components/Form.jsx
> +          console.info(result.text);
Mettre en place un toast, une info pour l'user (UX)

2023-11-14 08:58 UTC, jujuck commented on frontend/src/components/Form.jsx
> +        <label htmlFor="name">Nom :</label>
Intégrer l'input dans le label et enlever le htmlFor et l'id, pense à faire un composant avec props

2023-11-14 08:58 UTC, jujuck commented on frontend/src/components/form.css
> +  form > input {
Mettre des class

2023-11-15 14:35 UTC, sebastienbaquet approved these changes
ok

2023-11-15 15:57 UTC, aimach approved these changes

2023-11-15 15:57 UTC, merged