Ajout du composant du menu carousel
WildCodeSchool-2023-09/JS-RMT-React_If-Projet2-Obscuria pull request #6
Opened 2023-11-10 16:01 UTC by YounesSefiani

2023-11-10 16:04 UTC, GreG6431 approved these changes
Ok c'est tout bon

2023-11-14 09:13 UTC, jujuck requested changes

2023-11-14 09:13 UTC, jujuck commented on frontend/src/components/carouselMenu.jsx
> +          <div key={index.id} className="carousel-slide">
Pas d'index, utiliser l'id du movie

2023-11-14 09:13 UTC, jujuck commented on frontend/src/components/carouselMenu.jsx
> +const movieData = [
Faire une requete en back end avec une limit à 3, adapter le rendu en fonction de la data

2023-11-14 09:13 UTC, jujuck commented on frontend/package.json
>  }
Il manque le package de slider

2023-11-16 09:23 UTC, GreG6431 approved these changes

2023-11-16 15:07 UTC, aimach requested changes
- harmoniser les classes css svpppppp
- voir si la route  film/limit en front est toujours nécessaire
- supprimer le fichier home de pages si c'est juste un test

2023-11-16 15:07 UTC, aimach commented on frontend/src/App.css
il faut harmoniser vos noms de classe, vous avez du français, de l'anglais, du snake_case, du camelCase... merci de reprendre tout ça svp !

2023-11-16 15:07 UTC, aimach commented on frontend/src/main.jsx
> +    path: "/film/limit",
est-ce qu'on n'aurait pas besoin de l'enlever ce path ? parce que vous avez intégré le carrousel dans App, donc on n'a plus besoin de cette route, non ?

2023-11-16 15:07 UTC, aimach commented on frontend/src/pages/Home.jsx
Supprimer ce fichier si c'est un test :)

2023-11-17 09:51 UTC, jujuck approved these changes

2023-11-17 09:52 UTC, merged